# Generated by Django 5.1.5 on 2025-01-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eveniment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('data_eveniment', models.DateField()),
                ('locatie', models.CharField(max_length=255)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='evenimente/')),
            ],
        ),
    ]
