# Generated by Django 5.1.5 on 2025-01-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
